targets:
  $default:
    builders:
      freezed:
        options:
          build_extensions:
            'lib/{{path}}/{{file}}.dart':
              - 'lib/{{path}}/{{file}}.freezed.dart'
      json_serializable:
        options: {}
