enum AuthValidationError {
  usernameRequired,
  identifierRequired,
  usernameTooShort,
  usernameTooLong,
  usernameSpecialChars,
  emailRequired,
  invalidEmail,
  passwordRequired,
  passwordTooShort,
  passwordLeastOneLetter,
  passwordLeastOneDigit,
  passwordNoSpaces,
  confirmationRequired,
  passwordsDoNotMatch,
}
