export enum WaitingRoomEvents {
    GenerateCode = 'generateCode',
    GenerateCodeResponse = 'generateCodeResponse',
    CreateWaitingRoom = 'createWaitingRoom',
    WaitingRoomCreated = 'waitingRoomCreated',
    ToggleLockWaitingRoom = 'toggleLockWaitingRoom',
    WaitingRoomLocked = 'waitingRoomLocked',
    WaitingRoomUnlocked = 'waitingRoomUnlocked',

    CheckRoomExists = 'checkRoomExists',
    RoomExistsResponse = 'roomExistsResponse',
    GetReservedAvatars = 'getReservedAvatars',
    UpdateAvatarReserved = 'updateAvatarReserved',
    AvatarReservationFailed = 'avatarReservationFailed',
    ReserveAvatar = 'reserveAvatar',
    JoinWaitingRoom = 'joinWaitingRoom',
    JoinRoomResponse = 'joinRoomResponse',
    CreatePlayer = 'createPlayer',
    PlayerCreated = 'playerCreated',
    LeaveRoom = 'leaveRoom',
    LeaveRoomResponse = 'leaveRoomResponse',
    PlayerLeft = 'playerLeft',
    KickPlayer = 'kickPlayer',
    PlayerKicked = 'playerKicked',
    LeaveWaitingRoom = 'leaveWaitingRoom',

    SendMessageToWaitingRoom = 'sendMessageToWaitingRoom',
    MassMessage = 'massMessage',
    GetMessagesFromWaitingRoom = 'getMessagesFromWaitingRoom',
    GetMessagesResponse = 'getMessagesResponse',

    StartGame = 'startGame',
    CancelRoom = 'cancelRoom',
    RoomCanceled = 'roomCanceled',

    WaitingRoomError = 'waitingRoomError',
}
